server {
    listen 80;
    server_name _;

    # Port 80 = Web Statis CV
    location / {
        proxy_pass http://static-web:80;
        proxy_set_header Host $host;
    }

    # Web Dinamis di /app/
    location /app/ {
        proxy_pass http://dynamic-app:80/;
        proxy_set_header Host $host;
    }
}